version: '2.3'

services:
  statping:
    container_name: statping
    image: statping-next/statping-next:latest
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080

volumes:
  statping_data:
