version: '2.3'

services:

  statping_dev:
    container_name: statping_dev
    image: statping-next/statping-next:dev
    restart: on-failure
    volumes:
      - ./cmd:/go/src/github.com/statping-next/statping-next/cmd/
      - ./core:/go/src/github.com/statping-next/statping-next/core/
      - ./database:/go/src/github.com/statping-next/statping-next/database/
      - ./dev:/go/src/github.com/statping-next/statping-next/dev/
      - ./frontend:/go/src/github.com/statping-next/statping-next/frontend/
      - ./handlers:/go/src/github.com/statping-next/statping-next/handlers/
      - ./notifiers:/go/src/github.com/statping-next/statping-next/notifiers/
      - ./source:/go/src/github.com/statping-next/statping-next/source/
      - ./types:/go/src/github.com/statping-next/statping-next/types/
      - ./utils:/go/src/github.com/statping-next/statping-next/utils/
    environment:
      DB_CONN: sqlite
      API_SECRET: exampleapisecret
      NAME: Statping
      DOMAIN: http://localhost:8585
      DESCRIPTION: This is a dev environment with auto reloading!
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      PORT: 8585
    ports:
      - 8888:8888
      - 8585:8585
    networks:
      - statping
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8585/health || false"]
      timeout: 2s
      interval: 5s
      retries: 10

networks:
  statping:
